### ISSUE TITLE
Getting error when used with Multiclass TabNet classifier

### ISSUE THREAD

**Issue by VANRao-Stack** [Alibaba-MIIL/ASL#12]
I am getting the following error when I use the ASL loss function with the TabNet classifier: TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'. Any idea what I am doing wrong?

**Comment by mrT23** [comment]
we provide an example file, inference.py, that shows how to use our loss, and what are the dimensions and data-types of the inputs.

run inference.py and see the difference between it and your code
