### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by yanlin1995** [Alibaba-MIIL/ASL#14]
Why xs_neg = (xs_neg + self.clip).clamp(max=1) instead of xs_neg = (xs_neg - self.clip).clamp(min=0)?

**Comment by mrT23** [comment]
see https://github.com/Alibaba-MIIL/ASL/issues/10

**Comment by yanlin1995** [comment]
OK，I want to use this function in object detection. What are the hyperparameters used in the paper?

**Comment by mrT23** [comment]
we provide full hyperparameters details for each task in the paper appendix
