### ISSUE TITLE
annotations of NUS WIDE

### ISSUE THREAD

**Issue by JiaweiZhao-git** [Alibaba-MIIL/ASL#20]
Hi, I download the NUS WIDE from the url presented in paper's appendice [https://drive.google.com/file/d/0B7IzDz-4yH_HMFdiSE44R1lselE/view.]( https://drive.google.com/file/d/0B7IzDz-4yH_HMFdiSE44R1lselE/view). 

However, it seems there are only images without **annotations and your train/test split list**, could you please upload annotations and split list?

Thanks!

**Comment by mrT23** [comment]
to the best of my recollection, we obtained the labels from the official nus site.
notice that some images had no labels, so they were removed from the 70-30 split
anyway, I updated the model_zoo with the link
https://github.com/Alibaba-MIIL/ASL/blob/main/MODEL_ZOO.md

notice that this is a major contribution of our article to the community, that should be properly recognized.
obtaining and properly labeling nus-wide was hard.
no previous article has made even a remote attempt to share his "version" of nus-wide.
