### ISSUE TITLE
This code can run on CPU also?

### ISSUE THREAD

**Issue by PurveshChhajed** [Alibaba-MIIL/ASL#21]

**Comment by mrT23** [comment]
remove the ".cuda()" and yes

**Comment by Wan-Dou** [comment]
Hello,How to use  GIT+ https://github.com/mapillary/inplace_ abn.git @v1.0.11? When I run   validate.py  , I report an error: no module name 'inplace'_ abn'

**Comment by mrT23** [comment]
inplace-abn is an external dependency

i think it supports cpu only.

if you installation fails, try maybe installing an older tag, or ask in:
https://github.com/mapillary/inplace_abn

**Comment by PurveshChhajed** [comment]
> remove the ".cuda()" and yes

removing .cuda() works but as it us using inplace_abn, will this code run on CPU? (will inplace_abn works without GPU)
