### ISSUE TITLE
Wrong mAP from validate.py

### ISSUE THREAD

**Issue by kevin655** [Alibaba-MIIL/ASL#23]
Hello, I'm very interested in your novel work and try to run your validate.py file, but get totally wrong mAP: 
Actually, I run 
python validate.py  \
--model_name=tresnet_l \
--model_path=./models_local/MS_COCO_TRresNet_L_448_86.6.pth

but finally it printed out mAP score: 3.7.
Is something wrong with what I did?

**Comment by mrT23** [comment]
make sure you run on the correct dataset, MS-COCO 2014 split, multi label

when you run on the correct dataset, you will get the score mentioned, I validated it myself

**Comment by kevin655** [comment]
> make sure you run on the correct dataset, MS-COCO 2014 split, multi label
> 
> when you run on the correct dataset, you will get the score mentioned, I validated it myself

OK, thank you very much, I will try!

**Comment by kevin655** [comment]
> make sure you run on the correct dataset, MS-COCO 2014 split, multi label
> 
> when you run on the correct dataset, you will get the score mentioned, I validated it myself

Sorry to trouble you again, I did get the score mentioned with MS_COCO_TRresNet_L_448_86.6.pth as you mentioned above. However, the mAP was lower than 88.4 when I tried MS_COCO_TResNet_xl_640_88.4.pth with input_size 640. I think there might be some configs in your code that I have to change when test "ResNet_xl_640_88.4.pth"?  Thanks in advance.

**Comment by mrT23** [comment]
were you able to reproduce scores with "MS_COCO_TRresNet_L_448_86.6" (score should be 86.6) ? if you did, I think you are on the clear and can move on.

anyway, to reproduce the score with the larger model, make sure you input the correct resolution.

also, a strong tip for the future:  when you want to open a bug\problem, include full and complete details, including command line, logs, full output and so on.

**Comment by kevin655** [comment]
> were you able to reproduce scores with "MS_COCO_TRresNet_L_448_86.6" (score should be 86.6) ? if you did, I think you are on the clear and can move on.
> 
> anyway, to reproduce the score with the larger model, make sure you input the correct resolution.
> 
> also, a strong tip for the future: when you want to open a bug\problem, include full and complete details, including command line, logs, full output and so on.

Thank you for your sincere advice on how to ask a question, I did produce the score 86.6 and I will try again to reproduce the score with larger model (maybe there is some bug in my code). Anyway, I really appreciate your work.
Best wishes.
