### ISSUE TITLE
在使用BCE损失函数训练好的模型上，使用ASL微调模型，loss变大。

### ISSUE THREAD

**Issue by nimochuanzhang** [Alibaba-MIIL/ASL#24]
您好。
我的数据集一共有2个标签，每个标签有三个属性：a1、a2、a3，b1、b2、b3。
它们之间的比例是1,1.38807, 1.35329, 1.05098, 1.92411, 1.01199

但是我的样本不平衡，根据属性排列组合，共有9类图片:a1b1、a1b2、a1b3、a2b1、a2b2、a2b3、a3b1、a3b2、a3b3
它们之间的数量比例是：55，2.7，2.5，6.4，27，14.5，1，1，42

我首先使用BCEWithLogitsLoss进行训练，此时loss从1.5(始)------>0.11(终)，此时微平均是90%，宏平均是70%
然后在此基础上，使用您的ASL进行训练，此时loss从0.11-----1---->3------>2------>1(终)，此时微平均和宏平均反而都降低了。

请问：
1.宏平均比微平均差20%，是样本不平衡造成的吗
2.使用了ASL之后，精度反而降低，是参数设置的不对吗，应该如何设置参数（gamma_neg、gamma_pos、clip）。

**Comment by mrT23** [comment]
i cannot know tor answers specifics on your dataset.

to methodically check ASL on your dataset, follow the procedure i suggested here:
https://github.com/Alibaba-MIIL/ASL/issues/22#issuecomment-736721770

**Comment by nimochuanzhang** [comment]
> i cannot know tor answers specifics on your dataset.
> 
> to methodically check ASL on your dataset, follow the procedure i suggested here:
> [#22 (comment)](https://github.com/Alibaba-MIIL/ASL/issues/22#issuecomment-736721770)

OK, thank you for your help
