### ISSUE TITLE
Binary size of TresNet L - COCO vs OpenImage

### ISSUE THREAD

**Issue by wuhy08** [Alibaba-MIIL/ASL#34]
Hi @mrT23 

I am looking at the pretrained model you provided. I notice that the pretrained Tresnet-L for COCO and OpenImage have different binary size. Though COCO has fewer categories than OpenImage, its size is ~215MB whereas OpenImage's model is only 120MB. I wonder why this is the case?

Thank you!

**Comment by wuhy08** [comment]
With some investigation, I notice that OpenImage weights are float16 while COCO weights are float32. This might explain why.

**Comment by mrT23** [comment]
thanks for the investigation
we train on fp16, so this is just an artifact.

you can do all inference on fp16, and get the same results, even if the saved model was converted to fp32
