### ISSUE TITLE
Combining ASL with other technics?

### ISSUE THREAD

**Issue by wuhy08** [Alibaba-MIIL/ASL#35]
I am curious if you tried to combine ASL with other techniques like Spatial Regularization net (https://openaccess.thecvf.com/content_cvpr_2017/papers/Zhu_Learning_Spatial_Regularization_CVPR_2017_paper.pdf), GCN (https://arxiv.org/abs/1904.03582) , etc? Does that give you additional boost on AP score?

Thank you!

**Comment by mrT23** [comment]
When we entered the area of multi-label, our first attempt was with GCN networks.
in our tries, we could get a substantial improvement from it.

However, what bothered us the most is that this method is complicated, increases train and inference time, requires architecture modifications and has a lot of hyper-parameters 
That was basically our motivation for ASL - can't we improve the performance of multi-label networks without costly techniques that are very hard to implement and tune ?

I personally feel that this reflects a major gap in the requirements of academic conferences, compared to the requirements of actual practitioners - academic conferences seek for "novelty", at all cost. Practitioners seek for good tradeoff (scores, run-time, ease-of-use). We personally couldn't find a good tradeoff like this in GCN. If in your attempts you feel different, feel free to let us know :-)

**Comment by wuhy08** [comment]
Hi @mrT23 

Thank you so much for quick reply and detailed answer. I cannot agree more with your comment about the difference between academia and industry.

I tried Spatial Regularization Net + ASL because it was really easy to implement. The AP score could not improve when the model capacity was held as constant. So far it seems to me that ASL is the best (and simplest) way to get SOTA result.

Thank you again for your comment.
