### ISSUE TITLE
Dataset path

### ISSUE THREAD

**Issue by leoshine** [Alibaba-MIIL/ASL#37]
Is 

https://github.com/Alibaba-MIIL/ASL/blob/eb52197adb9761a0a8fe4aa8ef295918ce70cf61/train.py#L51-L52

should be:

```python
    data_path_val   = f'{args.data}/val2014'    # args.data
    data_path_train = f'{args.data}/train2014'  # args.data
```
?

**Comment by mrT23** [comment]
there are several variants of coco 2014 annotations

this code worked on my variant.

open a merge request that takes into account both variants, or just fixt it locally

**Comment by leoshine** [comment]
Thanks for the clarification.
