### ISSUE TITLE
hyper-parameters for reproducing results on MSCOCO

### ISSUE THREAD

**Issue by Junjzhan** [Alibaba-MIIL/ASL#40]
Thanks for the inspiring implementation :)

I'm having trouble to reproduce the results on MSCOCO with tresnet_m as backbone, 224 as input.
I have varied lr (1e-4 and 2e-4), batch_size (128 and 64), epochs (40/80 and 14/25) and only got around 79.+% mAP (which are lower than reported pre-train models).

I understand you can't share the original training code due to commerical reasons, can you provide your hyper-parameters for the reproduction? Seems these hyper-params influence the results.

**Comment by mrT23** [comment]
for tresnet_m 224 model in the site (posted a week ago), i used a better pretrain than the one you are using, so it's not unreasonable that you are getting lower scores (my pretrain is imagenet21K + special pre-train, yours is imagenet1K).

new prertrain models will be released in a couple of months along with a new article.

still, 79.0% is not a low score, i think it can even be considered SOTA compared to other articles (for resolution 224). 
try training with resolution 448, and i think you will reproduce the article results of tresnet_m.

**Comment by Junjzhan** [comment]
@mrT23 Thanks for the reply, I'll try it :)
