### ISSUE TITLE
Validation of nuswide checkpoint

### ISSUE THREAD

**Issue by SlongLiu** [Alibaba-MIIL/ASL#44]
Hi, thank you very much for sharing the dataset and split of nuswide dataset.

I try to reproduce the mAP 65.2 that reported in paper on nuswide dataset, but I can only get a mAP of 64.0 based on the dataset and checkpoint you provided.
Both the data and checkpoint I used are downloaded from the link you provided. The script is obtained by modifying the `validate.py` in this repo and could be found in https://github.com/SlongLiu/ASL_reproduce/blob/master/validate_nuswide.py. The log could be found in https://github.com/SlongLiu/ASL_reproduce/blob/master/nuswide_pt_test/log.txt. Could you give me some advice on the results?

Thanks very much again!

**Comment by mrT23** [comment]
i checked again on our environment, and indeed we get 65.2 mAP.

make sure to use a resolution of 240 (not 448).
that's the native resolution of the dataset

**Comment by SlongLiu** [comment]
Thanks for your kindly reply. I get 65.2 in the resolution of 240.
