### ISSUE TITLE
A question about the shifted probability?

### ISSUE THREAD

**Issue by ccc-pno** [Alibaba-MIIL/ASL#45]
Sorry, may I ask you a question？

In paper, you define the shifted probability, pm, as:  
       pm = max(p-m, 0)
But in code, you define it as:
      xs_neg = (xs_neg + self.clip).clamp(max=1)
      I think it is means:
      pm = min(1-p+m, 1)

Why ?

**Comment by mrT23** [comment]
https://github.com/Alibaba-MIIL/ASL/issues/10

**Comment by ccc-pno** [comment]
thanks！

**Comment by ccc-pno** [comment]
> #10

Thanks！
