### ISSUE TITLE
请问下 多标签分类 的数据label稀疏问题 怎么解决啊？

### ISSUE THREAD

**Issue by guotong1988** [Alibaba-MIIL/ASL#49]
多谢多谢多谢！

**Comment by mrT23** [comment]
what do you mean by "label sparseness" ? provide more details

**Comment by guotong1988** [comment]
input1 --> label1 --- 30% data
input2 --> label2 --- 30% data
input3 --> label3 --- 30% data
input4 --> label1,label2 --- 1% data
input4 --> label1,label2 --- 1% data

**Comment by mrT23** [comment]
if you have partial labeling, you can use the approach of  works like:
https://arxiv.org/pdf/1902.09720.pdf

its not related directly to our ASL loss.

**Comment by guotong1988** [comment]
THX！

**Comment by guotong1988** [comment]
THX！
