### ISSUE TITLE
Loss is causing the program to crash

### ISSUE THREAD

**Issue by ayziksha** [Alibaba-MIIL/ASL#5]
Hi,

I've tried running both the optimized and the non-optimized version of your loss and both caused an exception.
It seems that there is an issue with the self.target (is == None) in the optimized version and a shape issue with the non-optimized version.
What is the proper shape of the target in your loss?

Thanks

**Comment by mrT23** [comment]
i have added an example to 'infer'py' that shows how to calculate the loss.
(the target should be 1-hot vector)

also fixed a bug in AsymmetricLossOptimized.

thanks for noticing

```
    # example loss calculation
    output = model(tensor_batch)
    loss_func1 = AsymmetricLoss()
    loss_func2 = AsymmetricLossOptimized()
    target = output.clone()
    target[output < 0] = 0
    target[output >= 0] = 1
    loss1 = loss_func1(output, target)
    loss2 = loss_func2(output, target)
    assert abs((loss1.item()-loss2.item()))<1e-6
```
