### ISSUE TITLE
question about open images dataset

### ISSUE THREAD

**Issue by YehLi** [Alibaba-MIIL/ASL#52]
Hi, thanks for your great repo.
Open images dataset V6 contains human-verified labels and machine-generated labels. Do you use the machine-generated labels for training and testing?

**Comment by mrT23** [comment]
we want our **test** set to be clean as possible, so the machine-generated labels are not suited there.

for the article results, we didn't use the machine-generated labels in the **train** set.
we later added them there, and got an additional small improvement.
