### ISSUE TITLE
About the complete code for training on NUS-WIDE dataset

### ISSUE THREAD

**Issue by Sierkinhane** [Alibaba-MIIL/ASL#55]
Hi, thanks for your great works. Would you like to release the training and evaluation code for NUS-WIDE datasets?

**Comment by mrT23** [comment]
see validation code for nus wide in here:
https://github.com/Alibaba-MIIL/ASL/issues/44

regarding training code, I see no reason why the script in here:
https://github.com/Alibaba-MIIL/ASL/blob/main/train.py
wouldn't reproduce the article results (It reproduced MS-COCO results)
