### ISSUE TITLE
What is the value of FocalLoss alpha hyperprameter in ASL experiment?

### ISSUE THREAD

**Issue by sunlanchang** [Alibaba-MIIL/ASL#57]
In [original FocalLoss paper](https://arxiv.org/abs/1708.02002?source=post_page---------------------------), there are two hyperparameter in FocalLoss which are **alpha** and **gamma**. But I can't find alpha hyperparameter in your paper, so I want to know what is the value of alpha. Thank a lot!

**Comment by mrT23** [comment]
The article discusses it, read thoroughly (chapter 2.2)

**Comment by sunlanchang** [comment]
In chaper 2.2 of ASL paper, it said 

> In practice, [19] even suggested a weighting factor which favors background samples (α = 0.25). In section 3 we will show that simple linear weighting is insufficient to tackle the negative-positive imbalance issue in multi-label classification properly. For those reasons, we chose to avoid adding static weighting factors to our focusing formulation.

Is that equally mean the hyperparameter **alpha** of focal loss in figure5 is being set to 1.0? Thanks a lot!

**Comment by mrT23** [comment]
since the weighting is (α,1-α), equal factor is α=0.5

(or just remove alpha from focal loss equations, we are not using it to favor one over the other)

**Comment by sunlanchang** [comment]
> since the weighting is (α,1-α), equal factor is α=0.5
> 
> (or just remove alpha from focal loss equations, we are not using it to favor one over the other)

OK, I get you, thans a lot.
