### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute 'set_grad_enabled'

### ISSUE THREAD

**Issue by Allenstin** [Alibaba-MIIL/ASL#63]
最近想玩下多标签分类，同学给我推荐大神的这个代码。我按照requirements.txt要求，把环境装起来了，数据也下载下来了 。开始训练时，出现了这个错误：AttributeError: module 'torch._C' has no attribute 'set_grad_enabled'。我装的torch版本是1.7.1，cuda11.3。这个问题很奇怪，难道是装的torch版本有问题？

**Comment by Allenstin** [comment]
上午debug了下，发现pytorch1.6训练没有问题，pytorch1.7及以上存在上述问题。cuda11对于的pytorch版本全是1.7及以上，不过cuda11的GPU也有解决办法，在训练的时候，把disable_torch_grad_focal_loss设置为False，就不会报这种错误。白嫖的感觉真好，谢谢大佬的代码

**Comment by indersingh17188** [comment]
You can use torch.set_grad_enabled() instead of torch._C.set_grad_enabled().
