### ISSUE TITLE
This problem occurs when I use the ASLSingleLabel.

### ISSUE THREAD

**Issue by JonasZero** [Alibaba-MIIL/ASL#64]
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [64, 38]] is at version 3; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

I use a single label classification dataset.
The version of Pytorch I use is 1.7.1.

**Comment by mrT23** [comment]
try different loss. i don't think this is related to ASL.
if different loss does work, give reproducible code

**Comment by wangsssky** [comment]
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [64, 38]] is at version 3; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
> 
> I use a single label classification dataset.
> The version of Pytorch I use is 1.7.1.

Same Error, Did you solve it? Thanks

**Comment by mrT23** [comment]
provide full reproduction code

**Comment by Qidian213** [comment]
For me, the CrossEntropyLoss can work well, but when I change to use ASLSingleLabel  it occurs same error.

**Comment by mrT23** [comment]
i fixed the issue. no need to do
targets = copy.deepcopy(self.targets_classes)
which is very bad, and will cause you GPU memory leak along long training
