### ISSUE TITLE
The Assymetric Loss has negative value

### ISSUE THREAD

**Issue by thunanguyen** [Alibaba-MIIL/ASL#65]
I use the loss for my model (not TResNet) and sometimes it has a negative value. Is this a problem or normal?

**Comment by mrT23** [comment]
give dramatically more details and a reproduction code. check other losses as well

**Comment by thunanguyen** [comment]
Sorry because I'm bad at English but I try to be more detailed. So the model I use is the same with [ML-GCN](https://github.com/Megvii-Nanjing/ML-GCN) except I replace their loss with ASL loss with the default parameter and sometimes it gives the negative value of the loss. But when I try BCE loss (gamma_neg=gamma_pos=clip=0) and Focal Loss (gamma_neg=gamma_pos=2,clip=0) they do not give negative value. And I look in your paper, I think it should not give negative values, is that correct?

**Comment by mrT23** [comment]
it should not. i don't think mathematically it can give negative values, even for gamma>0,clip>0
check for bugs

**Comment by thunanguyen** [comment]
I directly use your code for the loss and the code from ML-GCN so I think it cant be bugs from the implementation.

**Comment by mrT23** [comment]
no.

bug can be, for example, numeric instability.
read the issue section. a ton of people reported problems, that were in practice their bugs.

all the article results were fully reproduced and validated.

**Comment by thunanguyen** [comment]
I've already look in issues section but I do not see any similar to my situation but for now I'll try different gamma parameter. Thank you for fast reply
