### ISSUE TITLE
Try to convert pretrain weight of TResNet_L to onnx face RuntimeError: ONNX export failed: Couldn't export Python operator InPlaceABN

### ISSUE THREAD

**Issue by Chenchienyuchen** [Alibaba-MIIL/ASL#73]
Thanks for such an interesting paper 👍

I want to convert pretrain weight of TResNet_L to onnx but pytorch jit and export to onnx not work with inplace-abn.

I follow the solution which is answered in issue 
https://github.com/mapillary/inplace_abn/issues/163
&
https://github.com/mapillary/inplace_abn/issues/210

Here is the steps how I implement.

1.
I replaced InPlaceABN(num_features=nf, activation=activation, activation_param=activation_param) on def conv2d_ABN( ) function with 
nn.BatchNorm2d(num_features=nf),
nn.LeakyReLU(activation_param)
in tresnet.py

2.
I remove  isinstance(m, InPlaceABN) on line 174 of tresnet.py
elif isinstance(m, nn.BatchNorm2d) or isinstance(m, InPlaceABN): into
elif isinstance(m, nn.BatchNorm2d)

After chang here is the tresnet.py code
`import torch

import torch.nn as nn

from torch.nn import Module as Module

from collections import OrderedDict

from src.models.tresnet.layers.anti_aliasing import AntiAliasDownsampleLayer

from .layers.avg_pool import FastAvgPool2d

from .layers.general_layers import SEModule, SpaceToDepthModule

from inplace_abn import InPlaceABN

class bottleneck_head(nn.Module):

    def __init__(self, num_features, num_classes, bottleneck_features=200):

        super(bottleneck_head, self).__init__()

        self.embedding_generator = nn.ModuleList()

        self.embedding_generator.append(nn.Linear(num_features, bottleneck_features))

        self.embedding_generator = nn.Sequential(*self.embedding_generator)

        self.FC = nn.Linear(bottleneck_features, num_classes)

    def forward(self, x):

        self.embedding = self.embedding_generator(x)

        logits = self.FC(self.embedding)

        return logits

def conv2d(ni, nf, stride):

    return nn.Sequential(

        nn.Conv2d(ni, nf, kernel_size=3, stride=stride, padding=1, bias=False),

        nn.BatchNorm2d(nf),

        nn.ReLU(inplace=True)

    )

def conv2d_ABN(ni, nf, stride, activation="leaky_relu", kernel_size=3, activation_param=1e-2, groups=1):

    return nn.Sequential(

        nn.Conv2d(ni, nf, kernel_size=kernel_size, stride=stride, padding=kernel_size // 2, groups=groups,

                  bias=False),

        # InPlaceABN(num_features=nf, activation=activation, activation_param=activation_param)

        nn.BatchNorm2d(num_features=nf),

        nn.LeakyReLU(activation_param)

    )

class BasicBlock(Module):

    expansion = 1

    def __init__(self, inplanes, planes, stride=1, downsample=None, use_se=True, anti_alias_layer=None):

        super(BasicBlock, self).__init__()

        if stride == 1:

            self.conv1 = conv2d_ABN(inplanes, planes, stride=1, activation_param=1e-3)

        else:

            if anti_alias_layer is None:

                self.conv1 = conv2d_ABN(inplanes, planes, stride=2, activation_param=1e-3)

            else:

                self.conv1 = nn.Sequential(conv2d_ABN(inplanes, planes, stride=1, activation_param=1e-3),

                                           anti_alias_layer(channels=planes, filt_size=3, stride=2))

        self.conv2 = conv2d_ABN(planes, planes, stride=1, activation="identity")

        self.relu = nn.ReLU(inplace=True)

        self.downsample = downsample

        self.stride = stride

        reduce_layer_planes = max(planes * self.expansion // 4, 64)

        self.se = SEModule(planes * self.expansion, reduce_layer_planes) if use_se else None

    def forward(self, x):

        if self.downsample is not None:

            residual = self.downsample(x)

        else:

            residual = x

        out = self.conv1(x)

        out = self.conv2(out)

        if self.se is not None: out = self.se(out)

        out += residual

        out = self.relu(out)

        return out

class Bottleneck(Module):

    expansion = 4

    def __init__(self, inplanes, planes, stride=1, downsample=None, use_se=True, anti_alias_layer=None):

        super(Bottleneck, self).__init__()

        self.conv1 = conv2d_ABN(inplanes, planes, kernel_size=1, stride=1, activation="leaky_relu",

                                activation_param=1e-3)

        if stride == 1:

            self.conv2 = conv2d_ABN(planes, planes, kernel_size=3, stride=1, activation="leaky_relu",

                                    activation_param=1e-3)

        else:

            if anti_alias_layer is None:

                self.conv2 = conv2d_ABN(planes, planes, kernel_size=3, stride=2, activation="leaky_relu",

                                        activation_param=1e-3)

            else:

                self.conv2 = nn.Sequential(conv2d_ABN(planes, planes, kernel_size=3, stride=1,

                                                      activation="leaky_relu", activation_param=1e-3),

                                           anti_alias_layer(channels=planes, filt_size=3, stride=2))

        self.conv3 = conv2d_ABN(planes, planes * self.expansion, kernel_size=1, stride=1,

                                activation="identity")

        self.relu = nn.ReLU(inplace=True)

        self.downsample = downsample

        self.stride = stride

        reduce_layer_planes = max(planes * self.expansion // 8, 64)

        self.se = SEModule(planes, reduce_layer_planes) if use_se else None

    def forward(self, x):

        if self.downsample is not None:

            residual = self.downsample(x)

        else:

            residual = x

        out = self.conv1(x)

        out = self.conv2(out)

        if self.se is not None: out = self.se(out)

        out = self.conv3(out)

        out = out + residual  # no inplace

        out = self.relu(out)

        return out

class TResNet(Module):

    def __init__(self, layers, in_chans=3, num_classes=1000, width_factor=1.0,

                 do_bottleneck_head=False,bottleneck_features=512):

        super(TResNet, self).__init__()

        # JIT layers

        space_to_depth = SpaceToDepthModule()

        anti_alias_layer = AntiAliasDownsampleLayer

        global_pool_layer = FastAvgPool2d(flatten=True)

        # TResnet stages

        self.inplanes = int(64 * width_factor)

        self.planes = int(64 * width_factor)

        conv1 = conv2d_ABN(in_chans * 16, self.planes, stride=1, kernel_size=3)

        layer1 = self._make_layer(BasicBlock, self.planes, layers[0], stride=1, use_se=True,

                                  anti_alias_layer=anti_alias_layer)  # 56x56

        layer2 = self._make_layer(BasicBlock, self.planes * 2, layers[1], stride=2, use_se=True,

                                  anti_alias_layer=anti_alias_layer)  # 28x28

        layer3 = self._make_layer(Bottleneck, self.planes * 4, layers[2], stride=2, use_se=True,

                                  anti_alias_layer=anti_alias_layer)  # 14x14

        layer4 = self._make_layer(Bottleneck, self.planes * 8, layers[3], stride=2, use_se=False,

                                  anti_alias_layer=anti_alias_layer)  # 7x7

        # body

        self.body = nn.Sequential(OrderedDict([

            ('SpaceToDepth', space_to_depth),

            ('conv1', conv1),

            ('layer1', layer1),

            ('layer2', layer2),

            ('layer3', layer3),

            ('layer4', layer4)]))

        # head

        self.embeddings = []

        self.global_pool = nn.Sequential(OrderedDict([('global_pool_layer', global_pool_layer)]))

        self.num_features = (self.planes * 8) * Bottleneck.expansion

        if do_bottleneck_head:

            fc = bottleneck_head(self.num_features, num_classes,

                                 bottleneck_features=bottleneck_features)

        else:

            fc = nn.Linear(self.num_features , num_classes)

        self.head = nn.Sequential(OrderedDict([('fc', fc)]))

        # model initilization

        for m in self.modules():#elif isinstance(m, nn.BatchNorm2d) or isinstance(m, nn.Sequential(nn.BatchNorm2d, "leaky_relu")):

            if isinstance(m, nn.Conv2d):

                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='leaky_relu')

            elif isinstance(m, nn.BatchNorm2d):

                nn.init.constant_(m.weight, 1)

                nn.init.constant_(m.bias, 0)

        # residual connections special initialization

        for m in self.modules():

            if isinstance(m, BasicBlock):

                m.conv2[1].weight = nn.Parameter(torch.zeros_like(m.conv2[1].weight))  # BN to zero

            if isinstance(m, Bottleneck):

                m.conv3[1].weight = nn.Parameter(torch.zeros_like(m.conv3[1].weight))  # BN to zero

            if isinstance(m, nn.Linear): m.weight.data.normal_(0, 0.01)

    def _make_layer(self, block, planes, blocks, stride=1, use_se=True, anti_alias_layer=None):

        downsample = None

        if stride != 1 or self.inplanes != planes * block.expansion:

            layers = []

            if stride == 2:

                # avg pooling before 1x1 conv

                layers.append(nn.AvgPool2d(kernel_size=2, stride=2, ceil_mode=True, count_include_pad=False))

            layers += [conv2d_ABN(self.inplanes, planes * block.expansion, kernel_size=1, stride=1,

                                  activation="identity")]

            downsample = nn.Sequential(*layers)

        layers = []

        layers.append(block(self.inplanes, planes, stride, downsample, use_se=use_se,

                            anti_alias_layer=anti_alias_layer))

        self.inplanes = planes * block.expansion

        for i in range(1, blocks): layers.append(

            block(self.inplanes, planes, use_se=use_se, anti_alias_layer=anti_alias_layer))

        return nn.Sequential(*layers)

    def forward(self, x):

        x = self.body(x)

        self.embeddings = self.global_pool(x)

        logits = self.head(self.embeddings)

        return logits

def TResnetM(model_params):

    """Constructs a medium TResnet model.

    """

    in_chans = 3

    num_classes = model_params['num_classes']

    model = TResNet(layers=[3, 4, 11, 3], num_classes=num_classes, in_chans=in_chans)

    return model

def TResnetL(model_params):

    """Constructs a large TResnet model.

    """

    in_chans = 3

    num_classes = model_params['num_classes']

    do_bottleneck_head = model_params['args'].do_bottleneck_head

    model = TResNet(layers=[4, 5, 18, 3], num_classes=num_classes, in_chans=in_chans, width_factor=1.2,

                    do_bottleneck_head=do_bottleneck_head)

    return model

def TResnetXL(model_params):

    """Constructs a xlarge TResnet model.

    """

    in_chans = 3

    num_classes = model_params['num_classes']

    model = TResNet(layers=[4, 5, 24, 3], num_classes=num_classes, in_chans=in_chans, width_factor=1.3)

    return model

`

3.Then I loaded the weights into those modules according to [readme](https://github.com/mapillary/inplace_abn/issues/163#issuecomment-802449498)
and re-inference .It can success to covert to onnx but the result is wrong.

Here is the inference code
`import torch
from src.helper_functions.helper_functions import parse_args
from src.loss_functions.losses import AsymmetricLoss, AsymmetricLossOptimized
from src.models import create_model
import argparse
# import matplotlib

# matplotlib.use('TkAgg')
# import matplotlib.pyplot as plt
from PIL import Image
import numpy as np

############################
import torch.nn as nn
from torch.nn import Module as Module
from collections import OrderedDict

parser = argparse.ArgumentParser(description='ASL MS-COCO Inference on a single image')

parser.add_argument('--model_path', type=str, default='./models_local/Open_ImagesV6_TRresNet_L_448.pth')
parser.add_argument('--pic_path', type=str, default='pics/000000000885.jpg')
parser.add_argument('--model_name', type=str, default='tresnet_l')
parser.add_argument('--input_size', type=int, default=448)
parser.add_argument('--dataset_type', type=str, default='OpenImages')
parser.add_argument('--th', type=float, default=None)

def fuse_bn_to_conv(bn_layer, conv_layer):
    # print('bn fuse')
    bn_st_dict = bn_layer.state_dict()
    conv_st_dict = conv_layer.state_dict()

    # BatchNorm params
    eps = bn_layer.eps
    mu = bn_st_dict['running_mean']
    var = bn_st_dict['running_var']
    gamma = bn_st_dict['weight']

    if 'bias' in bn_st_dict:
        beta = bn_st_dict['bias']
    else:
        beta = torch.zeros(gamma.size(0)).float().to(gamma.device)

    # Conv params
    W = conv_st_dict['weight']
    if 'bias' in conv_st_dict:
        bias = conv_st_dict['bias']
    else:
        bias = torch.zeros(W.size(0)).float().to(gamma.device)

    denom = torch.sqrt(var + eps)
    b = beta - gamma.mul(mu).div(denom)
    A = gamma.div(denom)
    bias *= A
    A = A.expand_as(W.transpose(0, -1)).transpose(0, -1)

    W.mul_(A)
    bias.add_(b)

    conv_layer.weight.data.copy_(W)
    if conv_layer.bias is None:
        conv_layer.bias = torch.nn.Parameter(bias)
    else:
        conv_layer.bias.data.copy_(bias)

def extract_layers(model):
    list_layers = []
    for n, p in model.named_modules():
        list_layers.append(n)
    return list_layers

def compute_next_bn(layer_name, resnet):
    list_layer = extract_layers(resnet)
    assert layer_name in list_layer
    if layer_name == list_layer[-1]:
        return None
    next_bn = list_layer[list_layer.index(layer_name) + 1]
    if extract_layer(resnet, next_bn).__class__.__name__ == 'BatchNorm2d':#InPlaceABN
        # print("\n",next_bn)
        return next_bn
    return None

def extract_layer(model, layer):
    layer = layer.split('.')
    module = model
    if hasattr(model, 'module') and layer[0] != 'module':
        module = model.module
    if not hasattr(model, 'module') and layer[0] == 'module':
        layer = layer[1:]
    for l in layer:
        if hasattr(module, l):
            if not l.isdigit():
                module = getattr(module, l)
            else:
                module = module[int(l)]
        else:
            return module
    return module

def set_layer(model, layer, val):
    layer = layer.split('.')
    module = model
    if hasattr(model, 'module') and layer[0] != 'module':
        module = model.module
    lst_index = 0
    module2 = module
    for l in layer:
        if hasattr(module2, l):
            if not l.isdigit():
                module2 = getattr(module2, l)
            else:
                module2 = module2[int(l)]
            lst_index += 1
    lst_index -= 1
    for l in layer[:lst_index]:
        if not l.isdigit():
            module = getattr(module, l)
        else:
            module = module[int(l)]
    l = layer[lst_index]
    setattr(module, l, val)

def fuse_bn(model):
    store_next_bn=""
    for n, m in model.named_modules():
        if isinstance(m, nn.Conv2d):
            next_bn = compute_next_bn(n, model)
            if next_bn is not None:
                store_next_bn=store_next_bn+next_bn+" "
                # next_bn_ = extract_layer(model, next_bn)
                # fuse_bn_to_conv(next_bn_, m)
                # set_layer(model, next_bn, nn.Identity())
                
    return store_next_bn

def main():
    print('ASL Example Inference code on a single image')

    # parsing args
    args = parse_args(parser)

    # setup model
    print('creating and loading the model...')
    state = torch.load(args.model_path)
    state_dict = torch.load(args.model_path)['model']
    args.num_classes = state['num_classes']
    model = create_model(args)
    store_next_bn=fuse_bn(model)
    model_dict = model.state_dict()
    # model_dict = model.body

    new_state_dict = OrderedDict()
    eps=1e-05
    for k, v in state['model'].items():#.keys() .items()
       
        ss = k.split('.')
        if ss[-1].endswith('weight'):
            find_bn_weight=k.split('.weight')[0]
            

        if store_next_bn.find(find_bn_weight)!=-1:
            v1 = torch.abs(v) + eps
        else:
            v1 = v
        new_state_dict[k] = v1
    # import pdb
    # pdb.set_trace()

  
    # model.load_state_dict(state['model'])
    model.load_state_dict(new_state_dict)
    model.cuda()
    model.eval()

    classes_list = np.array(list(state['idx_to_class'].values()))
   
    print('done\n')

    # doing inference
    print('loading image and doing inference...')
    im = Image.open(args.pic_path)
    import time
    tic=time.time()
    im_resize = im.resize((args.input_size, args.input_size))
    np_img = np.array(im_resize, dtype=np.uint8)
    tensor_img = torch.from_numpy(np_img).permute(2, 0, 1).float() / 255.0  # HWC to CHW
    tensor_batch = torch.unsqueeze(tensor_img, 0).cuda()
    
    output = torch.squeeze(torch.sigmoid(model(tensor_batch)))
    
    np_output = output.cpu().detach().numpy()
    
    detected_classes = classes_list[np_output > args.th]
    
    toc=time.time()
    print("spend time:",toc-tic)
    print("detected classes: {}".format(detected_classes))
    print('done\n')

    

    # doing inference
    # print('loading image and doing inference...')
    # im = Image.open(args.pic_path)
    # im_resize = im.resize((args.input_size, args.input_size))
    # np_img = np.array(im_resize, dtype=np.uint8)
    # tensor_img = torch.from_numpy(np_img).permute(2, 0, 1).float() / 255.0  # HWC to CHW
    # tensor_batch = torch.unsqueeze(tensor_img, 0).cuda()
    

    # x = torch.randn(1, 3, 448,448)
    # torch.onnx.export(model,
    #                       tensor_batch,
    #                       "asl.onnx",    
    #                       opset_version=10,
    #                       input_names=['input'],
    #                       output_names=['output']                     
    #                       )
    

   
    

if __name__ == '__main__':
    main()
`

**Could you provide onnx pretrain weight to me or help me to check if my implement steps is wrong.

Thank you very much!**

**Comment by mrT23** [comment]
Hi

TResNet can be easily converted to onnx. i have converted them in the past.
follow the steps listed below, don't reinvent the wheel, or do other stuff

1) update to latest ASL repo
2) edit the class "SpaceToDepthModule" to be:
```
class SpaceToDepthModule(nn.Module):
    def __init__(self, remove_model_jit=True): # True instead of false. JIT function cannot be converted.
        super().__init__()
        if not remove_model_jit:
            self.op = SpaceToDepthJit()
        else:
            self.op = SpaceToDepth()

    def forward(self, x):
        return self.op(x)
```
(you can pass the 'remove_model_jit' as an argument for something more modular)
3) 
After you create the model and load the proper weights, do:
```
model=InplacABN_to_ABN(model)
```
This will transfrom inplace bn to equivilent standart bn




If after these steps you encounter problems, let me know

Tal

**Comment by Chenchienyuchen** [comment]
> Hi
> 
> TResNet can be easily converted to onnx. i have converted them in the past. follow the steps listed below, don't reinvent the wheel, or do other stuff
> 
> 1. update to latest ASL repo
> 2. edit the class "SpaceToDepthModule" to be:
> 
> ```
> class SpaceToDepthModule(nn.Module):
>     def __init__(self, remove_model_jit=True): # True instead of false. JIT function cannot be converted.
>         super().__init__()
>         if not remove_model_jit:
>             self.op = SpaceToDepthJit()
>         else:
>             self.op = SpaceToDepth()
> 
>     def forward(self, x):
>         return self.op(x)
> ```
> 
> (you can pass the 'remove_model_jit' as an argument for something more modular) 3) After you create the model and load the proper weights, do:
> 
> ```
> model=InplacABN_to_ABN(model)
> ```
> 
> This will transfrom inplace bn to equivilent standart bn
> 
> If after these steps you encounter problems, let me know
> 
> Tal

problem solving,thanks!
