### ISSUE TITLE
Check map of OpenImagesV6 with TResNet_L Backbone after convert model to onnx 

### ISSUE THREAD

**Issue by Chenchienyuchen** [Alibaba-MIIL/ASL#75]
I want to check OpenImagesV6 map value with TResNet_L of onnx.

I  check validate.py is for Coco Dataset. Could you provide  validate script for OpenImagesV6 dataset ? Or can you give me some suggestion? Thanks a lot.

**Comment by mrT23** [comment]
i am not gonna provide a dedicated script for open-images.

my recommendation is just to run inference on several images, and see that results are logical and informative, and are the same for onnx and pytorch files.
