### ISSUE TITLE
Validation code

### ISSUE THREAD

**Issue by hellbell** [Alibaba-MIIL/ASL#8]
Hi, this repo is great!

Do you have any plan for releasing evaluation codes to see the reproduced results from the pretrained weights on MS-COCO and openimages?
I have tried to evaluate your models using this code (https://github.com/allenai/elastic/blob/master/multilabel_classify.py), but I failed to reproduce the scores and only got very low scores. 

Thanks!

**Comment by mrT23** [comment]
from a quick look at your code, the pre-procesing part needs to be different
see our example at infer.py.
specifically, try to replace

```
    # Data loading code
    normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                     std=[0.229, 0.224, 0.225])
    val_dataset = CocoDetection(os.path.join(args.data, 'val2014'),
                                os.path.join(args.data, 'annotations/instances_val2014.json'),
                                transforms.Compose([
                                    transforms.Resize((224, 224)),
                                    transforms.ToTensor(),
                                    normalize,
                                ]))
```

with something like:

```
    # Data loading code
    normalize = transforms.Normalize(mean=[0, 0, 0],
                                     std=[1, 1, 1])

    val_dataset = CocoDetection(os.path.join(args.data, 'val2014'),
                                os.path.join(args.data, 'annotations/instances_val2014.json'),
                                transforms.Compose([
                                    transforms.Resize((448, 448)),
                                    transforms.ToTensor(),
                                    normalize,
                                ]))
```

a tip:
try to run our model on a single image at your code base, and make sure you get 'reasonable' results, like we did at infer.py

**Comment by hellbell** [comment]
@mrT23 
Very thanks!
I have tried as you recommended, and think I got a reasonable result, F-overall=67.8 with precision 53% and recall 93%.
To get a higher score, should I adjust the threshold value? Currently, the threshold is zero.

**Comment by mrT23** [comment]
@hellbell 
the advantage of mAP is that it does not depend on a specific threshold.
maybe add that metric, to make sure you reproduce the article results

regarding threshold (th):
i guess your scores are for th=0.5, not th=0
the decision of a threshold is basically a tradeoff between false-negative and false positive.
visually, we found that the best results are obtained for 0.7<=th<=0.8.
as a rule-of-thumb, as we increase the level of asymmetry in the loss, we need higher threshold.

p.s.
i think your numbers are ok, this is what we got from a simillar model:
(OP: 53.32 OR: 93.36 OF1: 67.88)
```
2020-07-26 14:25:17 - INFO - mAP: 86.50022525467793
AP file was successfully saved
2020-07-26 14:25:17 - INFO - Saving validation results to ./outputs/final_val_data.pickle
2020-07-26 14:25:18 - INFO - th 0.5000
2020-07-26 14:25:18 - INFO - OP: 53.32 OR: 93.36 OF1: 67.88 CP: 55.91 CR: 91.29 CF1: 69.35
2020-07-26 14:25:18 - INFO - th 0.6000
2020-07-26 14:25:18 - INFO - OP: 68.20 OR: 89.32 OF1: 77.35 CP: 69.13 CR: 86.68 CF1: 76.92
2020-07-26 14:25:18 - INFO - th 0.7000
2020-07-26 14:25:18 - INFO - OP: 79.88 OR: 84.65 OF1: 82.19 CP: 79.81 CR: 81.83 CF1: 80.81
2020-07-26 14:25:18 - INFO - th 0.8000
2020-07-26 14:25:18 - INFO - OP: 88.15 OR: 79.21 OF1: 83.44 CP: 87.20 CR: 76.38 CF1: 81.43
2020-07-26 14:25:18 - INFO - th 0.9000
2020-07-26 14:25:18 - INFO - OP: 94.39 OR: 72.09 OF1: 81.75 CP: 93.72 CR: 69.41 CF1: 79.75
```

**Comment by hellbell** [comment]
@mrT23 
Great! 
I also just have reproduced your result by setting th=0.8 and got OF1=81.77.
Thanks again :)
