### ISSUE TITLE
getting difficulty in importing .pyi file 

### ISSUE THREAD

**Issue by PurveshChhajed** [Alibaba-MIIL/ASL#9]
File "/content/gdrive/My Drive/project/ASL/inplace_abn/inplace_abn/functions.py", line 8, in <module>

    from . import _backend
ImportError: cannot import name '_backend'

_backend.pyi file is in the same directory as functions.py

**Comment by mrT23** [comment]
you need to install inplace-abn properly

see the requirement.txt
